### ISSUE TITLE
Introduce incremental DB update mechanism

### ISSUE THREAD

**Issue by nsidorevich** [qaprosoft/zafira#1389]
## Description
Zafira should provide out-of-the box DB init and patch mechanism.

The following concepts should be addressed:

- Database should be initialized on first app startup
- On sequential startups database changes should be tracked and applied (if any)

Suggestion is to build that mechanism on top of the **Liquibase**.

## Implementation notes/challenges

- It is currently not clear what datasource should be used for Liquibase: the one that proxies connection ignores whatever schema is set at datasource level (since it's overrides it at connection level)
- The idea is to check if Zafira is running in 1T mode, and if so - apply changes to `zafira` schema only; otherwise - select all tenants from `management` schema and sequentially apply patches to them. 
- It is not clear how schema should be initialized on first startup - Liquibase requires schema to exist so it can put its tables inside; while there's no out-of-the box solution in Zafira to serve that purpose.

## Tasks

- [x] Integrate Liquibase with **dbaccess** module, test incremental update against single tenant
- [x] Come up with schema init mechanism
- [x] Create custom DbPatcher component that will apply incremental changes to **all schemas** in case when Zafira runs as a MT deployment

UPD 04/29/2019 by @tsvrko on behalf of @nikitasidorevich : postponed till further investigation, initial implementation approach was underestimated
